src/Tateeda.Clires/Tateeda.Clires/Areas/Admin/Controllers/VisitController.cs
namespace Tateeda.Clires.Areas.Admin.Controllers
{
    #region Usings

    using Tateeda.Clires.Data.UOW;

    using global::System;

    using global::System.Threading;

    using global::System.Web.Mvc;

    using Tateeda.Clires.Areas.Admin.Model.Study;
    using Tateeda.Clires.Core.Data.Enums;
    using Tateeda.Clires.Core.Visits;
    using Tateeda.Clires.Extensions;
    using Tateeda.Clires.System;

    #endregion

    [Authorize(Roles = GlobalVariables.RoleSystemAdmin)]
    public class VisitController : BaseController
    {
        public ActionResult Index()
        {
            var model = new VisitViewModel();
            return View(model);
        }

        public JsonResult CreateVisit(VisitViewModel model)
        {
            //ModelState.Remove("StudyId");
            //model.StudyId = GlobalVariables.CurrentStudyId;

            if (model.Id == 0)
            {
                ModelState.Remove("Id");
                TryValidateModel(model);
            }

            if (!ModelState.IsValid)
            {
                return Json("alert('Error!');", JsonRequestBehavior.DenyGet);
            }

            if (model.ParentVisitId < 1) model.ParentVisitId = null;

            if (model.Id > 0)
            {
                return UpdateVisit(model);
            }

            var visit = model.ToEntity();
            visit.CreatedOn = DateTime.UtcNow;
            visit.CreatedBy = Thread.CurrentPrincipal.Identity.Name;
            visit.Status = (int)EntityStatusType.Current;

            using (var adminUow = DependencyResolver.Current.GetService<IAdminUnitOfWork>())
            {
                adminUow.VisitRepository.Insert(visit);
                adminUow.Commit();
            }
            return Json("vis.vm.loadVisits(" + model.StudyId + ");", JsonRequestBehavior.DenyGet);
        }

        private JsonResult UpdateVisit(VisitViewModel model)
        {
            using (var adminUow = DependencyResolver.Current.GetService<IAdminUnitOfWork>())
            {
                var visit = model.ToEntity();
                visit.UpdatedOn = DateTime.UtcNow;
                visit.UpdatedBy = Thread.CurrentPrincipal.Identity.Name;
                visit.Status = (int)EntityStatusType.Current;
                if (model.ParentVisitId > 0)
                {
                    var parent = adminUow.VisitRepository.GetById(model.ParentVisitId);
                    if (parent != null) parent.HasChild = true;
                }
                else
                {
                    visit.ParentVisitId = null;
                }
                adminUow.VisitRepository.Update(visit);
                adminUow.Commit();

                return Json("vis.vm.loadVisits(" + model.StudyId + ");", JsonRequestBehavior.DenyGet);
            }
        }
    }
}

src/Tateeda.Clires/Tateeda.Clires/Areas/Study/Views/Shared/_FormLinkView.cshtml
@using Tateeda.Clires.Areas.Admin.Model.Forms
@using Tateeda.Clires.Core.Data.Enums
@model IEnumerable<Tateeda.Clires.Areas.Admin.Model.Forms.FormViewModel>

@{
    var defForms = @Model.Where(f => f.FormTypeId == (int)FormType.DefaultForm).ToList();
    var labForms = @Model.Where(f => f.FormTypeId == (int)FormType.LabForm).ToList();
    var apptId = ViewBag.AppointementId + "";
}

<div class="row-fluid">
    <div class="row-fluid">
        <div class="span1 offset1">
            <h4>Forms:</h4>
        </div>
        <div class="span6">
            <ol>
                @if (defForms != null && defForms.Count > 0)
                {
                    foreach (FormViewModel f in defForms)
                    {                            
                    <li>
                        @using (Html.BeginForm("FormSubmission", "Visit", new { @area = "Study" }, FormMethod.Post,
                                    new { @class = "form-inline", @id = f.Id + "_frm" }))
                        {                                                       
                            <input type="hidden" name="vid" value="@apptId"/>
                            <button type="submit" class="btn-link">@f.Name</button>
                            <input type="hidden" name="fid" value="@f.Id"/>
                            
                        }
                    </li>
                    }
                }

            </ol>
        </div>
    </div>
    <hr />
    <div class="row-fluid">
        <div class="span1 offset1">
            <h4>Labs:</h4>
        </div>
        <div class="span6">
            <ol>

                @if (labForms != null && labForms.Count > 0)
                {
                    foreach (FormViewModel l in labForms)
                    {
                    <li>
                        @using (Html.BeginForm("FormSubmission", "Visit", new { @area = "Study" }, FormMethod.Post,
                                    new { @class = "form-inline", @id = l.Id + "_frm" }))
                        {
                            <input type="hidden" name="fid" value="@l.Id"/>
                            <input type="hidden" name="vid" value="@apptId"/>
                            <button type="submit" class="btn-link">@l.Name</button>
                        }
                    </li>
                    }
                }
            </ol>
        </div>
    </div>
</div>

src/Tateeda.Clires/Tateeda.Clires/Areas/Study/Views/Shared/_SubjectMedictionView.cshtml
@using Tateeda.Clires.Core.Data.EF
@using Tateeda.Clires.Utility
@model ISubjectDrug
@{
	var enumHelper = new EnumerationHelper();
	const int DoseTypeId = 17;
	const int MultipleTrialsId = 18;
	const int ReasonStoppedId = 15;
	const int ReasonTypeId = 14;
	const int TreatmentInducedId = 16;
}

@using (Ajax.BeginForm("AddSubjectDrug",
	new { @area = "Study", @controller = "Visit" },
	new AjaxOptions { HttpMethod = "POST", OnComplete = "OnCompleteWithCallback", OnFailure = "OnFailure" },
	new { @class = "" }))
{
	<input type="hidden" name="SubjectId" value="@ViewBag.SubjectId"/>
	
	<div class="content-wrapper">
		<div class="row-fluid">

			<div class="row-fluid">
				<div class="span12">
					<span class="control-label">Drug:<b class="required">* </b></span>
					<input class="input-xxlarge" placeholder="Enter Drug name" required="required" id="drugSearch" name="searchDrugName" /><br />
					<input type="hidden" id="drugId" name="DrugId" />
					<select id="drugSearchResult" size="10" class="hide input-xxlarge" style="position: absolute; z-index: 20;"
						data-bind="
							options: med.vm.drugs(),
							optionsText: 'Name',
							optionsValue: 'Id',
							value: med.vm.drugVal">
					</select>
				</div>
			</div>
			<div>
				<br />
			</div>
			<div class="row-fluid">
				<div class="span4">
					<label class="control-label">Max Dose Used:<b class="required">*</b></label>
				</div>
				<div class="span4">
					<label class="control-label">Units:<b class="required">*</b></label>
				</div>
				<div class="span4">
					<label class="control-label">Multiple Trials:<b class="required">*</b></label>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<input type="number" required="required" name="Dosage" class="number-only input-large" />
				</div>
				<div class="span4">
					<div class="controls">
						@Html.DropDownListFor(m => m.DosageType, enumHelper.GetOptions(DoseTypeId),
							new Dictionary<string, object>
								{
									{"class", "input-large"},
									{"data-bind", "value: $data.DosageType"},
									{"required", "required"}
								})
					</div>
				</div>
				<div class="span4">
					<div class="controls">
						@Html.DropDownListFor(m => m.MultipleTrialsId, enumHelper.GetOptions(MultipleTrialsId),
							new Dictionary<string, object>
								{
									{"class", "input-large"},
									{"data-bind", "value: $data.MultipleTrialsId"},
									{"required", "required"}
								})
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<label class="control-label">Reason Stopped:<b class="required">*</b></label>
				</div>
				<div class="span4">
					<label class="control-label">Treatment Induced Activation:<b class="required">*</b></label>
				</div>
				<div class="span4">
					<label class="control-label">Response Type:<b class="required">*</b></label>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<div class="controls">
						@Html.DropDownListFor(m => m.ReasonStoppedId, enumHelper.GetOptions(ReasonStoppedId),
							new Dictionary<string, object>
								{
									{"class", "input-large"},
									{"data-bind", "value: $data.ReasonStoppedId"},
									{"required", "required"}
								})
					</div>
				</div>
				<div class="span4">
					<div class="controls">
						@Html.DropDownListFor(m => m.TreatmentInducedId, enumHelper.GetOptions(TreatmentInducedId),
							new Dictionary<string, object>
								{
									{"class", "input-large"},
									{"data-bind", "value: $data.TreatmentInducedId"},
									{"required", "required"}
								})
					</div>
				</div>
				<div class="span4">
					<div class="controls">
						@Html.DropDownListFor(m => m.ReasonTypeId, enumHelper.GetOptions(ReasonTypeId),
							new Dictionary<string, object>
								{
									{"class", "input-large"},
									{"data-bind", "value: $data.ReasonTypeId"},
									{"required", "required"}
								})
					</div>
				</div>
			</div>
			<div class="row-fluid">

				<div class="span4">
					<label class="control-label">Start Date:<b class="required">*</b></label>
				</div>
				<div class="span4">
					<label class="control-label">End Date:</label>
				</div>
				<div class="span4">
					<label class="control-label">Used Before Study Started:</label>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<input type="date" name="StartDate" class="input-large date" id="startDate" required="required" />
				</div>
				<div class="span4">
					<input type="date" name="EndDate" class="input-large date" id="endDate" />
				</div>
				<div class="span4">
					<input type="checkbox" name="IsBeforeStudy" />
				</div>
			</div>
			<div class="row-fluid">
				<div class="span4">
					<label class="control-label">MD Notes:</label>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<input type="text" name="MdNotes" class="input-full-width" />
				</div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2 button">
				<input type="submit" class="btn-primary btn" value="Add" />
			</div>
			<div class="span4 alert-success">
				<div id="historyMsg"></div>
			</div>
		</div>
	</div>
}